name: HSP
favicon: null
layout_spectrum: 0.980071515776217
typography_spectrum: 0.8554230416193604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4172556037083268
  lightness: 0.6767714417073876
  saturation: 0.5118560390546918
  rhythmicContrast: 0.05600705370306969
purpose: []
